require("gigglebiscuits.pckr")
require("gigglebiscuits.nvimtree")
require("gigglebiscuits.git")
require("gigglebiscuits.telescope")
require("gigglebiscuits.treesitter")
require("gigglebiscuits.lsp")
require("gigglebiscuits.cmp")
